<?php
/**
 * Donor Portal — Aftercare Support
 */

include __DIR__ . '/inc/header.view.php';
include __DIR__ . '/inc/sidebar.view.php';
?>

<main class="d-content">
    <div class="d-content__header">
        <div style="display: flex; justify-content: space-between; align-items: flex-start;">
            <div>
                <h2><i class="fas fa-hand-holding-medical text-accent"></i> Aftercare Support</h2>
                <p>Track your follow-up appointments and review support requests.</p>
            </div>
            <div class="d-status d-status--success">
                <div class="d-status__dot"></div>
                Active Support
            </div>
        </div>
    </div>
    
    <div class="d-content__body">
        
        <!-- Centered Calendar Section -->
        <div style="display: flex; justify-content: center; margin-bottom: 3rem;">
            <div class="d-widget" style="width: 100%; max-width: 600px;">
                <div class="d-widget__header">
                    <div class="d-widget__title"><i class="fas fa-calendar text-accent"></i> Appointments Calendar</div>
                </div>
                
                <div class="d-widget__body">
                    <div id="calendar-container" style="padding: 30px;">
                        <!-- Calendar will be generated by JavaScript -->
                    </div>
                </div>
            </div>
        </div>

        <!-- Appointment Categories/Tabs -->
        <div style="display: flex; justify-content: center; gap: 1.5rem; margin-bottom: 3rem; flex-wrap: wrap;">
            <button class="d-btn d-btn--lg d-btn--primary" onclick="switchTab('schedule')" id="tab-schedule" style="padding: 12px 28px; font-weight: 600; border-radius: 8px; min-width: 200px;">
                <i class="fas fa-plus-circle"></i> Schedule an Appointment
            </button>
            <button class="d-btn d-btn--lg" onclick="switchTab('requested')" id="tab-requested" style="padding: 12px 28px; font-weight: 600; border-radius: 8px; min-width: 200px; background: #e5e7eb; color: #374151; border: none;">
                <i class="fas fa-list"></i> Support Request
            </button>
            <button class="d-btn d-btn--lg" onclick="switchTab('aftercare')" id="tab-aftercare" style="padding: 12px 28px; font-weight: 600; border-radius: 8px; min-width: 200px; background: #e5e7eb; color: #374151; border: none;">
                <i class="fas fa-heart"></i> contact us
            </button>
        </div>

        <!-- Content Sections -->
        <div class="d-dashboard-grid" style="grid-template-columns: 1fr; gap: 2rem;">
            
            <!-- My Appointments -->
            <div class="d-widget" id="section-schedule">
                <div class="d-widget__header" style="display: flex; justify-content: space-between; align-items: center;">
                    <div class="d-widget__title"><i class="far fa-calendar-alt text-accent"></i> My Appointments</div>
                </div>
                
                <div class="d-widget__body" style="padding: 0;">
                    <div class="d-table-wrap" style="border: none; border-radius: 0 0 var(--r) var(--r);">
                        <table class="d-table">
                            <thead>
                                <tr>
                                    <th>Date & Time</th>
                                    <th>Type</th>
                                    <th>Description</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if (!empty($appointments)): foreach ($appointments as $apt): ?>
                                    <tr>
                                        <td><i class="far fa-clock text-accent"></i> <?= date('M d, Y - h:i A', strtotime($apt->appointment_date)) ?></td>
                                        <td style="font-weight: 600; color: var(--blue-800);"><?= htmlspecialchars($apt->appointment_type) ?></td>
                                        <td style="color: var(--g500);">
                                            <?php
                                                $desc = trim((string)($apt->description ?? ''));
                                                $rej = trim((string)($apt->rejection_reason ?? ''));
                                                if (($apt->status ?? '') === 'Cancelled' && $rej !== '') {
                                                    echo htmlspecialchars(($desc !== '' ? $desc . ' — ' : '') . 'Rejected: ' . $rej);
                                                } else {
                                                    echo htmlspecialchars($desc !== '' ? $desc : 'N/A');
                                                }
                                            ?>
                                        </td>
                                        <td>
                                            <?php 
                                                $statusClass = 'd-status--neutral';
                                                if ($apt->status === 'Requested') $statusClass = 'd-status--pending';
                                                if ($apt->status === 'Scheduled') $statusClass = 'd-status--info';
                                                if ($apt->status === 'Completed') $statusClass = 'd-status--success';
                                                if ($apt->status === 'Cancelled' || $apt->status === 'Missed') $statusClass = 'd-status--danger';
                                            ?>
                                            <div class="d-status <?= $statusClass ?>" style="display: inline-flex; padding: 0.25rem 0.5rem; font-size: 0.75rem;">
                                                <div class="d-status__dot"></div>
                                                <?= htmlspecialchars($apt->status) ?>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; else: ?>
                                    <tr>
                                        <td colspan="4" style="text-align: center; padding: 2rem; color: var(--g500); font-style: italic;">
                                            No aftercare appointments scheduled yet.
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!-- Support Request -->
            <div class="d-widget" id="section-requested" style="display: none;">
                <div class="d-widget__header" style="display: flex; justify-content: space-between; align-items: center;">
                    <div class="d-widget__title"><i class="fas fa-envelope-open-text text-accent"></i> Support Request</div>
                    <button class="d-btn d-btn--sm d-btn--primary" onclick="openSupportRequestModal()"><i class="fas fa-plus"></i> New Request</button>
                </div>
                
                <div class="d-widget__body" style="padding: 0;">
                    <div class="d-table-wrap" style="border: none; border-radius: 0 0 var(--r) var(--r);">
                        <table class="d-table">
                            <thead>
                                <tr>
                                    <th>Date Submitted</th>
                                    <th>Reason</th>
                                    <th>Amount</th>
                                    <th>Description</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if (!empty($support_requests)): foreach ($support_requests as $req): ?>
                                    <tr>
                                        <td><i class="far fa-calendar text-accent"></i> <?= date('M d, Y', strtotime($req->created_at)) ?></td>
                                        <td style="font-weight: 500; color: var(--blue-800);"><?= htmlspecialchars($req->reason) ?></td>
                                        <td style="font-weight: 700; color: var(--blue-800);">
                                            <?php if (isset($req->amount) && $req->amount !== '' && is_numeric($req->amount)): ?>
                                                LKR <?= number_format((float)$req->amount, 2) ?>
                                            <?php else: ?>
                                                —
                                            <?php endif; ?>
                                        </td>
                                        <td style="color: var(--g500);">
                                            <?php
                                                $fullDesc = (string)($req->description ?? '');
                                                $markerPos = strpos($fullDesc, '[Hospital Review]');
                                                $userDesc = $markerPos !== false ? trim(substr($fullDesc, 0, $markerPos)) : trim($fullDesc);
                                                $reviewReason = '';
                                                if (preg_match('/\[Hospital Review\][\s\S]*?\nReason:\s*([^\n]+)/i', $fullDesc, $m)) {
                                                    $reviewReason = trim((string)$m[1]);
                                                }
                                            ?>
                                            <div><?= htmlspecialchars($userDesc !== '' ? $userDesc : 'N/A') ?></div>
                                            <?php if (strtoupper((string)($req->status ?? '')) === 'REJECTED' && $reviewReason !== ''): ?>
                                                <div style="margin-top: 6px; color: var(--blue-800); font-weight: 600;">
                                                    Rejection reason: <?= htmlspecialchars($reviewReason) ?>
                                                </div>
                                            <?php endif; ?>
                                        </td>
                                        <td>
                                            <?php 
                                                $statusClass = 'd-status--warning'; 
                                                if ($req->status === 'APPROVED') $statusClass = 'd-status--success';
                                                if ($req->status === 'REJECTED') $statusClass = 'd-status--danger';
                                            ?>
                                            <div class="d-status <?= $statusClass ?>" style="display: inline-flex; padding: 0.25rem 0.5rem; font-size: 0.75rem;">
                                                <div class="d-status__dot"></div>
                                                <?= htmlspecialchars($req->status ?: 'PENDING') ?>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; else: ?>
                                    <tr>
                                        <td colspan="5" style="text-align: center; padding: 2rem; color: var(--g500); font-style: italic;">
                                            No support requests submitted yet.
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            
            <!-- Aftercare Support Section -->
            <div id="section-aftercare" style="display: none;">
                <div class="d-widget" style="background: linear-gradient(135deg, var(--blue-50), var(--white)); border-left: 4px solid var(--blue-600);">
                    <div class="d-widget__body" style="display: flex; gap: 1.5rem; align-items: center;">
                        <div style="font-size: 3rem; color: var(--blue-300);">
                            <i class="fas fa-user-md"></i>
                        </div>
                        <div>
                            <h3 style="color: var(--blue-900); font-weight: 700; font-size: 1.25rem; margin-bottom: 0.5rem;">Need Aftercare Assistance?</h3>
                            <p style="color: var(--blue-800); font-size: 0.9rem; margin-bottom: 1rem;">If you require financial or medical support for post-donation care, you can request it through our aftercare administrators.</p>
                            <div style="display: flex; gap: 1.5rem; font-size: 0.9rem; color: var(--slate); font-weight: 500;">
                                <span><i class="fas fa-envelope text-accent"></i> aftercare@lifeconnect.lk</span>
                                <span><i class="fas fa-phone text-accent"></i> +94 11 234 5678</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</main>

<!-- Appointment Modal -->
<div id="appointmentModal" style="display: none; position: fixed; z-index: 1000; left: 0; top: 0; width: 100%; height: 100%; background: rgba(0, 0, 0, 0.5);">
    <div style="background: white; margin: 10% auto; padding: 2rem; border-radius: 8px; width: 90%; max-width: 500px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem;">
            <h3 style="margin: 0; color: #1f2937; font-size: 1.25rem;"><i class="fas fa-calendar-plus text-accent"></i> Book an Appointment</h3>
            <button onclick="closeAppointmentModal()" style="background: none; border: none; font-size: 1.5rem; cursor: pointer; color: #6b7280;">&times;</button>
        </div>
        
        <form id="appointmentForm" onsubmit="submitAppointment(event)">
            <div style="margin-bottom: 1.5rem;">
                <label style="display: block; margin-bottom: 0.5rem; font-weight: 600; color: #374151;">Appointment Date & Time <span style="color: #ef4444;">*</span></label>
                <input type="datetime-local" id="appointmentDateInput" required style="width: 100%; padding: 0.75rem; border: 1px solid #d1d5db; border-radius: 6px; font-size: 1rem;">
            </div>
            
            <div style="margin-bottom: 1.5rem;">
                <label style="display: block; margin-bottom: 0.5rem; font-weight: 600; color: #374151;">Hospital <span style="color: #ef4444;">*</span></label>
                <select id="appointmentHospitalInput" required style="width: 100%; padding: 0.75rem; border: 1px solid #d1d5db; border-radius: 6px; font-size: 1rem;">
                    <option value="">Select Hospital</option>
                    <?php if (!empty($hospitals)): foreach ($hospitals as $hosp): ?>
                        <option value="<?= htmlspecialchars($hosp->registration_number ?? $hosp->id) ?>"><?= htmlspecialchars($hosp->name) ?></option>
                    <?php endforeach; endif; ?>
                </select>
            </div>

            <div style="margin-bottom: 1.5rem;">
                <label style="display: block; margin-bottom: 0.5rem; font-weight: 600; color: #374151;">Appointment Type <span style="color: #ef4444;">*</span></label>
                <select id="appointmentTypeInput" required style="width: 100%; padding: 0.75rem; border: 1px solid #d1d5db; border-radius: 6px; font-size: 1rem;">
                    <option value="">Select Type</option>
                    <option value="Follow-up">Follow-up Checkup</option>
                    <option value="Health Review">Health Review</option>
                    <option value="Medical Consultation">Medical Consultation</option>
                    <option value="Laboratory Tests">Laboratory Tests</option>
                    <option value="Other">Other</option>
                </select>
            </div>
            
            <div style="margin-bottom: 1.5rem;">
                <label style="display: block; margin-bottom: 0.5rem; font-weight: 600; color: #374151;">Reason for Appointment</label>
                <textarea id="appointmentReasonInput" placeholder="Please describe the reason or any specific concerns..." style="width: 100%; padding: 0.75rem; border: 1px solid #d1d5db; border-radius: 6px; font-size: 1rem; font-family: inherit; resize: vertical; min-height: 100px;"></textarea>
            </div>
            
            <div style="display: flex; gap: 1rem;">
                <button type="submit" class="d-btn d-btn--primary" style="flex: 1; padding: 0.75rem; border: none; border-radius: 6px; font-weight: 600; cursor: pointer; background: #2563eb; color: white;">
                    <i class="fas fa-check"></i> Book Appointment
                </button>
                <button type="button" onclick="closeAppointmentModal()" class="d-btn d-btn--secondary" style="flex: 1; padding: 0.75rem; border: 1px solid #d1d5db; border-radius: 6px; font-weight: 600; cursor: pointer; background: white; color: #374151;">
                    Cancel
                </button>
            </div>
        </form>
    </div>
</div>

<!-- Support Request Modal -->
<div id="supportRequestModal" style="display: none; position: fixed; z-index: 1000; left: 0; top: 0; width: 100%; height: 100%; background: rgba(0, 0, 0, 0.5);">
    <div style="background: white; margin: 10% auto; padding: 2rem; border-radius: 8px; width: 90%; max-width: 500px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem;">
            <h3 style="margin: 0; color: #1f2937; font-size: 1.25rem;"><i class="fas fa-envelope-open-text text-accent"></i> Submit Support Request</h3>
            <button onclick="closeSupportRequestModal()" style="background: none; border: none; font-size: 1.5rem; cursor: pointer; color: #6b7280;">&times;</button>
        </div>
        
        <form id="supportRequestForm" onsubmit="submitSupportRequest(event)">
            <div style="margin-bottom: 1.5rem;">
                <label style="display: block; margin-bottom: 0.5rem; font-weight: 600; color: #374151;">Hospital <span style="color: #ef4444;">*</span></label>
                <select id="supportHospitalInput" required style="width: 100%; padding: 0.75rem; border: 1px solid #d1d5db; border-radius: 6px; font-size: 1rem;">
                    <option value="">Select Hospital</option>
                    <?php if (!empty($hospitals)): foreach ($hospitals as $hosp): ?>
                        <option value="<?= htmlspecialchars($hosp->registration_number ?? $hosp->id) ?>"><?= htmlspecialchars($hosp->name) ?></option>
                    <?php endforeach; endif; ?>
                </select>
            </div>

            <div style="margin-bottom: 1.5rem;">
                <label style="display: block; margin-bottom: 0.5rem; font-weight: 600; color: #374151;">Type of Support Required <span style="color: #ef4444;">*</span></label>
                <select id="supportReasonInput" required style="width: 100%; padding: 0.75rem; border: 1px solid #d1d5db; border-radius: 6px; font-size: 1rem;">
                    <option value="">Select Support Type</option>
                    <option value="Medical Support">Medical Support</option>
                    <option value="Financial Support">Financial Support</option>
                    <option value="Transportation Assistance">Transportation Assistance</option>
                    <option value="Travel Cost Support">Travel Cost Support</option>
                    <option value="Test Cost Support">Test Cost Support</option>
                    <option value="Medication Support">Medication Support</option>
                    <option value="Counselling Support">Counselling Support</option>
                    <option value="Other">Other</option>
                </select>
            </div>

            <div style="margin-bottom: 1.5rem;">
                <label style="display: block; margin-bottom: 0.5rem; font-weight: 600; color: #374151;">Amount (LKR) <span style="color: #6b7280; font-weight: 500;">(optional)</span></label>
                <input id="supportAmountInput" type="number" min="0" step="0.01" placeholder="e.g., 2500" style="width: 100%; padding: 0.75rem; border: 1px solid #d1d5db; border-radius: 6px; font-size: 1rem;" />
            </div>
            
            <div style="margin-bottom: 1.5rem;">
                <label style="display: block; margin-bottom: 0.5rem; font-weight: 600; color: #374151;">Detailed Description</label>
                <textarea id="supportDescriptionInput" placeholder="Please provide details about your support request..." style="width: 100%; padding: 0.75rem; border: 1px solid #d1d5db; border-radius: 6px; font-size: 1rem; font-family: inherit; resize: vertical; min-height: 120px;"></textarea>
            </div>
            
            <div style="display: flex; gap: 1rem;">
                <button type="submit" class="d-btn d-btn--primary" style="flex: 1; padding: 0.75rem; border: none; border-radius: 6px; font-weight: 600; cursor: pointer; background: #2563eb; color: white;">
                    <i class="fas fa-paper-plane"></i> Submit Request
                </button>
                <button type="button" onclick="closeSupportRequestModal()" class="d-btn d-btn--secondary" style="flex: 1; padding: 0.75rem; border: 1px solid #d1d5db; border-radius: 6px; font-weight: 600; cursor: pointer; background: white; color: #374151;">
                    Cancel
                </button>
            </div>
        </form>
    </div>
</div>

<script>
const DEFAULT_HOSPITAL_REG_NO = <?php echo json_encode((string)($default_hospital_registration_no ?? '')); ?>;

// Appointments data from PHP
const appointmentsData = <?php echo json_encode(array_map(function($apt) {
    return [
        'date' => date('Y-m-d', strtotime($apt->appointment_date)),
        'time' => date('h:i A', strtotime($apt->appointment_date)),
        'type' => $apt->appointment_type,
        'description' => $apt->description ?? '',
        'status' => $apt->status
    ];
}, $appointments)); ?>;

// Calendar generation
class AppointmentCalendar {
    constructor(containerId, appointmentsArray) {
        this.container = document.getElementById(containerId);
        this.appointments = appointmentsArray;
        this.currentDate = new Date();
        this.render();
    }

    getDaysInMonth(date) {
        return new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate();
    }

    getFirstDayOfMonth(date) {
        return new Date(date.getFullYear(), date.getMonth(), 1).getDay();
    }

    hasAppointment(day) {
        const dateStr = `${this.currentDate.getFullYear()}-${String(this.currentDate.getMonth() + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        return this.appointments.some(apt => apt.date === dateStr);
    }

    getAppointmentsForDay(day) {
        const dateStr = `${this.currentDate.getFullYear()}-${String(this.currentDate.getMonth() + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        return this.appointments.filter(apt => apt.date === dateStr);
    }

    previousMonth() {
        this.currentDate.setMonth(this.currentDate.getMonth() - 1);
        this.render();
    }

    nextMonth() {
        this.currentDate.setMonth(this.currentDate.getMonth() + 1);
        this.render();
    }

    render() {
        const monthYear = this.currentDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
        const daysInMonth = this.getDaysInMonth(this.currentDate);
        const firstDay = this.getFirstDayOfMonth(this.currentDate);

        let html = `
            <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto;">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
                    <button onclick="calendar.previousMonth()" style="background: #f3f4f6; border: 1px solid #e5e7eb; padding: 8px 12px; border-radius: 6px; cursor: pointer; color: #374151; font-weight: 500;">
                        <i class="fas fa-chevron-left"></i> Previous
                    </button>
                    <h3 style="margin: 0; color: #1f2937; font-size: 1.25rem; font-weight: 600;">${monthYear}</h3>
                    <button onclick="calendar.nextMonth()" style="background: #f3f4f6; border: 1px solid #e5e7eb; padding: 8px 12px; border-radius: 6px; cursor: pointer; color: #374151; font-weight: 500;">
                        Next <i class="fas fa-chevron-right"></i>
                    </button>
                </div>
                
                <div style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 8px;">
        `;

        // Day headers
        const dayLabels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
        dayLabels.forEach(label => {
            html += `<div style="text-align: center; font-weight: 700; color: #6b7280; padding: 8px; font-size: 0.9rem;">${label}</div>`;
        });

        // Empty cells for days before month starts
        for (let i = 0; i < firstDay; i++) {
            html += `<div style="padding: 8px;"></div>`;
        }

        // Days of month - make all days clickable for booking
        for (let day = 1; day <= daysInMonth; day++) {
            const hasApt = this.hasAppointment(day);
            const apts = this.getAppointmentsForDay(day);
            const bgColor = hasApt ? '#dbeafe' : '#f9fafb';
            const borderColor = hasApt ? '#3b82f6' : '#e5e7eb';
            const hoverStyle = 'cursor: pointer; transition: all 0.2s ease;';

            html += `
                <div style="background: ${bgColor}; border: 2px solid ${borderColor}; border-radius: 8px; padding: 8px; text-align: center; min-height: 60px; display: flex; flex-direction: column; align-items: center; justify-content: center; ${hoverStyle}" 
                     onmouseover="this.style.background='#eff6ff'; this.style.borderColor='#0ea5e9';" 
                     onmouseout="this.style.background='${bgColor}'; this.style.borderColor='${borderColor}';"
                     onclick="${hasApt ? `showAppointmentDetails(${day})` : `openAppointmentForDate(${day})`}">
                    <div style="font-weight: ${hasApt ? '700' : '500'}; color: ${hasApt ? '#1e40af' : '#6b7280'}; font-size: 1rem;">${day}</div>
                    ${hasApt ? `<div style="font-size: 0.7rem; color: #3b82f6; margin-top: 4px;"><i class="fas fa-check-circle"></i> ${apts.length} appt</div>` : `<div style="font-size: 0.7rem; color: #9ca3af; margin-top: 4px;">Book</div>`}
                </div>
            `;
        }

        html += `</div>`;
        this.container.innerHTML = html;
    }
}

// Show appointment details for a day
function showAppointmentDetails(day) {
    const apts = calendar.getAppointmentsForDay(day);
    const monthYear = calendar.currentDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
    
    if (apts.length === 0) return;

    let details = `<h4 style="margin-top: 0; color: #1f2937;">Appointments on ${monthYear} ${day}</h4>`;
    
    apts.forEach(apt => {
        let statusColor = '#ef4444';
        let statusIcon = 'clock';
        if (apt.status === 'Completed') {
            statusColor = '#10b981';
            statusIcon = 'check-circle';
        } else if (apt.status === 'Scheduled') {
            statusColor = '#3b82f6';
            statusIcon = 'calendar-check';
        }

        details += `
            <div style="background: #f9fafb; border-left: 4px solid ${statusColor}; padding: 12px; margin-bottom: 10px; border-radius: 4px;">
                <div style="display: flex; justify-content: space-between; align-items: start;">
                    <div>
                        <div style="font-weight: 600; color: #1f2937; margin-bottom: 4px;">
                            <i class="fas fa-${statusIcon}" style="color: ${statusColor}; margin-right: 6px;"></i> ${apt.type}
                        </div>
                        <div style="font-size: 0.9rem; color: #6b7280; margin-bottom: 4px;">
                            <i class="fas fa-clock"></i> ${apt.time}
                        </div>
                        <div style="font-size: 0.9rem; color: #4b5563;">${apt.description || 'No additional notes'}</div>
                    </div>
                    <span style="background: ${statusColor}; color: white; padding: 4px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600; white-space: nowrap;">
                        ${apt.status}
                    </span>
                </div>
            </div>
        `;
    });

    alert(details);
}

// Open appointment modal for a specific date
function openAppointmentForDate(day) {
    const date = new Date(calendar.currentDate.getFullYear(), calendar.currentDate.getMonth(), day);
    const dateStr = date.toISOString().split('T')[0];
    document.getElementById('appointmentDateInput').value = dateStr + 'T09:00';
    openAppointmentModal();
}

// Open appointment modal
function openAppointmentModal() {
    const modal = document.getElementById('appointmentModal');
    if (modal) {
        modal.style.display = 'block';
        document.body.style.overflow = 'hidden';
    }
}

// Close appointment modal
function closeAppointmentModal() {
    const modal = document.getElementById('appointmentModal');
    if (modal) {
        modal.style.display = 'none';
        document.body.style.overflow = 'auto';
        document.getElementById('appointmentForm').reset();
    }
}

// Submit appointment form
function submitAppointment(e) {
    e.preventDefault();
    
    const appointmentDate = document.getElementById('appointmentDateInput').value;
    const appointmentType = document.getElementById('appointmentTypeInput').value;
    const description = document.getElementById('appointmentReasonInput').value;
    const hospitalRegistrationNo = document.getElementById('appointmentHospitalInput').value;
    
    if (!appointmentDate || !appointmentType || !hospitalRegistrationNo) {
        alert('Please fill in all required fields');
        return;
    }
    
    const formData = new FormData();
    formData.append('appointment_date', appointmentDate);
    formData.append('appointment_type', appointmentType);
    formData.append('description', description);
    formData.append('hospital_registration_no', hospitalRegistrationNo);
    
    fetch('<?php echo ROOT; ?>/donor/create-appointment', {
        method: 'POST',
        body: formData
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            alert('Appointment booked successfully!');
            closeAppointmentModal();
            location.reload();
        } else {
            alert('Error: ' + data.message);
        }
    })
    .catch(error => {
        console.error('Error:', error);
        alert('An error occurred while booking the appointment');
    });
}

// Open support request modal
function openSupportRequestModal() {
    const modal = document.getElementById('supportRequestModal');
    if (modal) {
        modal.style.display = 'block';
        document.body.style.overflow = 'hidden';

        // Auto-select previously used hospital if available
        const hospSel = document.getElementById('supportHospitalInput');
        if (hospSel && !hospSel.value) {
            const saved = (localStorage.getItem('lc_aftercare_hospital_reg_no') || '').trim();
            const candidate = saved || String(DEFAULT_HOSPITAL_REG_NO || '').trim();
            if (candidate) {
                const hasOpt = Array.from(hospSel.options).some(o => String(o.value) === candidate);
                if (hasOpt) hospSel.value = candidate;
            }
        }
    }
}

// Close support request modal
function closeSupportRequestModal() {
    const modal = document.getElementById('supportRequestModal');
    if (modal) {
        modal.style.display = 'none';
        document.body.style.overflow = 'auto';
        document.getElementById('supportRequestForm').reset();
    }
}

// Submit support request form
function submitSupportRequest(e) {
    e.preventDefault();
    
    const reason = document.getElementById('supportReasonInput').value;
    const description = document.getElementById('supportDescriptionInput').value;
    const hospitalRegistrationNo = document.getElementById('supportHospitalInput').value;
    const amount = (document.getElementById('supportAmountInput')?.value || '').trim();
    
    if (!reason || !hospitalRegistrationNo) {
        alert('Please fill in all required fields');
        return;
    }
    
    const formData = new FormData();
    formData.append('reason', reason);
    formData.append('description', description);
    formData.append('hospital_registration_no', hospitalRegistrationNo);

    // Remember for next time
    if (hospitalRegistrationNo) {
        localStorage.setItem('lc_aftercare_hospital_reg_no', String(hospitalRegistrationNo));
    }
    if (amount !== '') formData.append('amount', amount);
    
    fetch('<?php echo ROOT; ?>/donor/submit-support-request', {
        method: 'POST',
        body: formData,
        credentials: 'same-origin'
    })
    .then(async (response) => {
        const raw = await response.text();
        let data;
        try {
            data = raw ? JSON.parse(raw) : {};
        } catch (e) {
            throw new Error('Server returned an invalid response. Please try again.');
        }
        if (!response.ok) {
            throw new Error(data.message || 'Request failed');
        }
        return data;
    })
    .then(data => {
        if (data && data.success) {
            alert('Support request submitted successfully!');
            closeSupportRequestModal();
            location.reload();
        } else {
            alert('Error: ' + ((data && data.message) ? data.message : 'Unable to submit request'));
        }
    })
    .catch(error => {
        console.error('Error:', error);
        alert(error && error.message ? error.message : 'An error occurred while submitting the request');
    });
}

// Tab switching function
function switchTab(tabName) {
    // Hide all sections
    document.getElementById('section-schedule').style.display = 'none';
    document.getElementById('section-requested').style.display = 'none';
    document.getElementById('section-aftercare').style.display = 'none';
    
    // Reset all button styles
    document.getElementById('tab-schedule').style.background = '#e5e7eb';
    document.getElementById('tab-schedule').style.color = '#374151';
    document.getElementById('tab-requested').style.background = '#e5e7eb';
    document.getElementById('tab-requested').style.color = '#374151';
    document.getElementById('tab-aftercare').style.background = '#e5e7eb';
    document.getElementById('tab-aftercare').style.color = '#374151';
    
    // Show selected section and highlight button
    if (tabName === 'schedule') {
        document.getElementById('section-schedule').style.display = 'block';
        document.getElementById('tab-schedule').style.background = '#2563eb';
        document.getElementById('tab-schedule').style.color = 'white';
    } else if (tabName === 'requested') {
        document.getElementById('section-requested').style.display = 'block';
        document.getElementById('tab-requested').style.background = '#2563eb';
        document.getElementById('tab-requested').style.color = 'white';
    } else if (tabName === 'aftercare') {
        document.getElementById('section-aftercare').style.display = 'block';
        document.getElementById('tab-aftercare').style.background = '#2563eb';
        document.getElementById('tab-aftercare').style.color = 'white';
    }
}

// Initialize calendar
const calendar = new AppointmentCalendar('calendar-container', appointmentsData);

// Close modals when clicking outside
window.onclick = function(event) {
    const appointmentModal = document.getElementById('appointmentModal');
    const supportRequestModal = document.getElementById('supportRequestModal');
    
    if (event.target === appointmentModal) {
        closeAppointmentModal();
    }
    if (event.target === supportRequestModal) {
        closeSupportRequestModal();
    }
}
</script>

<?php include __DIR__ . '/inc/footer.view.php'; ?>
