<?php
/**
 * Custodian Portal — Certificates View
 * Route: GET /custodian/certificates
 * Active page key: certificates
 */

$page_icon     = 'fa-certificate';
$page_heading  = 'Certificates';
$page_subtitle = 'Official letters and certificates issued upon successful donation completion.';

ob_start();
?>

<!-- Page Header -->
<?php include __DIR__ . '/partials/page-header.php'; ?>

<div class="cp-content__body">

    <div class="cp-notice cp-notice--info">
        <i class="fas fa-circle-info"></i>
        <div>
            <strong>Certificates are issued after completion</strong>
            <p>Certificates and official letters are generated by LifeConnect and the receiving institution only after the donation is fully completed and verified.</p>
        </div>
    </div>

    <!-- ── Certificate Cards ──────────────────────────────────────────── -->
    <div class="cp-grid-2">

        <!-- Body Donation Certificate -->
        <div class="cp-section-card">
            <div class="cp-section-card__header">
                <div class="cp-section-card__title">
                    <i class="fas fa-certificate"></i> Body Donation Certificate
                </div>
                <span class="cp-badge cp-badge--neutral">Locked</span>
            </div>
            <div class="cp-section-card__body">
                <div class="cp-empty-state">
                    <div class="cp-empty-state__icon"><i class="fas fa-lock"></i></div>
                    <div class="cp-empty-state__msg">Not yet issued</div>
                    <div class="cp-empty-state__sub">Issued after body acceptance is confirmed</div>
                </div>
                <div class="cp-form-actions" style="justify-content:center;">
                    <button class="cp-btn cp-btn--outline" disabled title="Certificate not yet issued">
                        <i class="fas fa-download"></i> Download Certificate
                    </button>
                </div>
            </div>
        </div>

        <!-- Organ Donation Certificate -->
        <div class="cp-section-card">
            <div class="cp-section-card__header">
                <div class="cp-section-card__title">
                    <i class="fas fa-certificate"></i> Organ Donation Certificate
                </div>
                <span class="cp-badge cp-badge--neutral">Locked</span>
            </div>
            <div class="cp-section-card__body">
                <div class="cp-empty-state">
                    <div class="cp-empty-state__icon"><i class="fas fa-lock"></i></div>
                    <div class="cp-empty-state__msg">Not yet issued</div>
                    <div class="cp-empty-state__sub">Issued after organ acceptance is confirmed</div>
                </div>
                <div class="cp-form-actions" style="justify-content:center;">
                    <button class="cp-btn cp-btn--outline" disabled title="Certificate not yet issued">
                        <i class="fas fa-download"></i> Download Certificate
                    </button>
                </div>
            </div>
        </div>

        <!-- Institution Thank-You Letter -->
        <div class="cp-section-card">
            <div class="cp-section-card__header">
                <div class="cp-section-card__title">
                    <i class="fas fa-envelope"></i> Institution Letter
                </div>
                <span class="cp-badge cp-badge--neutral">Locked</span>
            </div>
            <div class="cp-section-card__body">
                <div class="cp-empty-state">
                    <div class="cp-empty-state__icon"><i class="fas fa-lock"></i></div>
                    <div class="cp-empty-state__msg">Not yet issued</div>
                    <div class="cp-empty-state__sub">Sent by the receiving medical institution</div>
                </div>
                <div class="cp-form-actions" style="justify-content:center;">
                    <button class="cp-btn cp-btn--outline" disabled title="Letter not yet issued">
                        <i class="fas fa-download"></i> Download Letter
                    </button>
                </div>
            </div>
        </div>

        <!-- LifeConnect Commemorative Certificate -->
        <div class="cp-section-card">
            <div class="cp-section-card__header">
                <div class="cp-section-card__title">
                    <i class="fas fa-award"></i> LifeConnect Commemorative Certificate
                </div>
                <span class="cp-badge cp-badge--neutral">Locked</span>
            </div>
            <div class="cp-section-card__body">
                <div class="cp-empty-state">
                    <div class="cp-empty-state__icon"><i class="fas fa-lock"></i></div>
                    <div class="cp-empty-state__msg">Not yet issued</div>
                    <div class="cp-empty-state__sub">Issued by LifeConnect upon case closure</div>
                </div>
                <div class="cp-form-actions" style="justify-content:center;">
                    <button class="cp-btn cp-btn--outline" disabled title="Certificate not yet issued">
                        <i class="fas fa-download"></i> Download Certificate
                    </button>
                </div>
            </div>
        </div>

    </div><!-- /.cp-grid-2 -->

</div><!-- /.cp-content__body -->

<?php
$page_content = ob_get_clean();
require dirname(__DIR__) . '/layouts/custodian.layout.php';
?>
